export const SUPPORTED_PLATFORMS: Record < string, string > = {
	"32x": "32X",
	"3do": "3DO",
	"arcade": "Arcade",
	"atari-2600": "Atari 2600",
	"dreamcast": "Dreamcast",
	"epic-store": "Epic Games Store",
	"flathub": "Flathub",
	"gb": "Game Boy",
	"gba": "Game Boy Advance",
	"gbc": "Game Boy Color",
	"gc": "GameCube",
	"genesis": "Genesis",
	"gog": "GOG",
	"jaguar": "Jaguar",
	"n64": "Nintendo 64",
	"neo-geo": "Neo Geo",
	"nes": "Nintendo",
	"ps1": "PlayStation",
	"ps2": "PlayStation 2",
	"psp": "PlayStation Portable",
	"saturn": "Saturn",
	"sega-cd": "Sega CD",
	"sgg": "Game Gear",
	"sms": "Master System",
	"snes": "Super Nintendo",
	"tg-16": "TurboGrafx-16"
};
